/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UltimaPartnershipRouteImport } from './routes/ultima-partnership'
import { Route as SurveyAuditRouteImport } from './routes/survey-audit'
import { Route as SuKienRouteImport } from './routes/su-kien'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as QisignalsRouteImport } from './routes/qisignals'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HocVienRouteImport } from './routes/hoc-vien'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DoiTacRouteImport } from './routes/doi-tac'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuKienIndexRouteImport } from './routes/su-kien.index'
import { Route as SuKienIdRouteImport } from './routes/su-kien.$id'
import { Route as SanPhamIdRouteImport } from './routes/san-pham.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminLessonsRouteImport } from './routes/_authenticated/admin.lessons'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminCmsRouteImport } from './routes/_authenticated/admin.cms'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'

const UltimaPartnershipRoute = UltimaPartnershipRouteImport.update({
  id: '/ultima-partnership',
  path: '/ultima-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyAuditRoute = SurveyAuditRouteImport.update({
  id: '/survey-audit',
  path: '/survey-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SuKienRoute = SuKienRouteImport.update({
  id: '/su-kien',
  path: '/su-kien',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const QisignalsRoute = QisignalsRouteImport.update({
  id: '/qisignals',
  path: '/qisignals',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HocVienRoute = HocVienRouteImport.update({
  id: '/hoc-vien',
  path: '/hoc-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DoiTacRoute = DoiTacRouteImport.update({
  id: '/doi-tac',
  path: '/doi-tac',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuKienIndexRoute = SuKienIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuKienRoute,
} as any)
const SuKienIdRoute = SuKienIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuKienRoute,
} as any)
const SanPhamIdRoute = SanPhamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SanPhamRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLessonsRoute =
  AuthenticatedAdminLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsRoute = AuthenticatedAdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/doi-tac': typeof DoiTacRoute
  '/features': typeof FeaturesRoute
  '/hoc-vien': typeof HocVienRoute
  '/home': typeof HomeRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/qisignals': typeof QisignalsRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/su-kien': typeof SuKienRouteWithChildren
  '/survey-audit': typeof SurveyAuditRoute
  '/ultima-partnership': typeof UltimaPartnershipRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/san-pham/$id': typeof SanPhamIdRoute
  '/su-kien/$id': typeof SuKienIdRoute
  '/su-kien/': typeof SuKienIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/doi-tac': typeof DoiTacRoute
  '/features': typeof FeaturesRoute
  '/hoc-vien': typeof HocVienRoute
  '/home': typeof HomeRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/qisignals': typeof QisignalsRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/survey-audit': typeof SurveyAuditRoute
  '/ultima-partnership': typeof UltimaPartnershipRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/su-kien/$id': typeof SuKienIdRoute
  '/su-kien': typeof SuKienIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/doi-tac': typeof DoiTacRoute
  '/features': typeof FeaturesRoute
  '/hoc-vien': typeof HocVienRoute
  '/home': typeof HomeRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/qisignals': typeof QisignalsRoute
  '/san-pham': typeof SanPhamRouteWithChildren
  '/su-kien': typeof SuKienRouteWithChildren
  '/survey-audit': typeof SurveyAuditRoute
  '/ultima-partnership': typeof UltimaPartnershipRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/san-pham/$id': typeof SanPhamIdRoute
  '/su-kien/$id': typeof SuKienIdRoute
  '/su-kien/': typeof SuKienIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/doi-tac'
    | '/features'
    | '/hoc-vien'
    | '/home'
    | '/portal'
    | '/pricing'
    | '/qisignals'
    | '/san-pham'
    | '/su-kien'
    | '/survey-audit'
    | '/ultima-partnership'
    | '/admin'
    | '/san-pham/$id'
    | '/su-kien/$id'
    | '/su-kien/'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/events'
    | '/admin/leads'
    | '/admin/lessons'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/submissions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/doi-tac'
    | '/features'
    | '/hoc-vien'
    | '/home'
    | '/portal'
    | '/pricing'
    | '/qisignals'
    | '/san-pham'
    | '/survey-audit'
    | '/ultima-partnership'
    | '/san-pham/$id'
    | '/su-kien/$id'
    | '/su-kien'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/events'
    | '/admin/leads'
    | '/admin/lessons'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/submissions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/doi-tac'
    | '/features'
    | '/hoc-vien'
    | '/home'
    | '/portal'
    | '/pricing'
    | '/qisignals'
    | '/san-pham'
    | '/su-kien'
    | '/survey-audit'
    | '/ultima-partnership'
    | '/_authenticated/admin'
    | '/san-pham/$id'
    | '/su-kien/$id'
    | '/su-kien/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/cms'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/lessons'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DoiTacRoute: typeof DoiTacRoute
  FeaturesRoute: typeof FeaturesRoute
  HocVienRoute: typeof HocVienRoute
  HomeRoute: typeof HomeRoute
  PortalRoute: typeof PortalRoute
  PricingRoute: typeof PricingRoute
  QisignalsRoute: typeof QisignalsRoute
  SanPhamRoute: typeof SanPhamRouteWithChildren
  SuKienRoute: typeof SuKienRouteWithChildren
  SurveyAuditRoute: typeof SurveyAuditRoute
  UltimaPartnershipRoute: typeof UltimaPartnershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ultima-partnership': {
      id: '/ultima-partnership'
      path: '/ultima-partnership'
      fullPath: '/ultima-partnership'
      preLoaderRoute: typeof UltimaPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey-audit': {
      id: '/survey-audit'
      path: '/survey-audit'
      fullPath: '/survey-audit'
      preLoaderRoute: typeof SurveyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/su-kien': {
      id: '/su-kien'
      path: '/su-kien'
      fullPath: '/su-kien'
      preLoaderRoute: typeof SuKienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qisignals': {
      id: '/qisignals'
      path: '/qisignals'
      fullPath: '/qisignals'
      preLoaderRoute: typeof QisignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-vien': {
      id: '/hoc-vien'
      path: '/hoc-vien'
      fullPath: '/hoc-vien'
      preLoaderRoute: typeof HocVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doi-tac': {
      id: '/doi-tac'
      path: '/doi-tac'
      fullPath: '/doi-tac'
      preLoaderRoute: typeof DoiTacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/su-kien/': {
      id: '/su-kien/'
      path: '/'
      fullPath: '/su-kien/'
      preLoaderRoute: typeof SuKienIndexRouteImport
      parentRoute: typeof SuKienRoute
    }
    '/su-kien/$id': {
      id: '/su-kien/$id'
      path: '/$id'
      fullPath: '/su-kien/$id'
      preLoaderRoute: typeof SuKienIdRouteImport
      parentRoute: typeof SuKienRoute
    }
    '/san-pham/$id': {
      id: '/san-pham/$id'
      path: '/$id'
      fullPath: '/san-pham/$id'
      preLoaderRoute: typeof SanPhamIdRouteImport
      parentRoute: typeof SanPhamRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lessons': {
      id: '/_authenticated/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AuthenticatedAdminLessonsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms': {
      id: '/_authenticated/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AuthenticatedAdminCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCmsRoute: typeof AuthenticatedAdminCmsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminLessonsRoute: typeof AuthenticatedAdminLessonsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCmsRoute: AuthenticatedAdminCmsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminLessonsRoute: AuthenticatedAdminLessonsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SanPhamRouteChildren {
  SanPhamIdRoute: typeof SanPhamIdRoute
}

const SanPhamRouteChildren: SanPhamRouteChildren = {
  SanPhamIdRoute: SanPhamIdRoute,
}

const SanPhamRouteWithChildren =
  SanPhamRoute._addFileChildren(SanPhamRouteChildren)

interface SuKienRouteChildren {
  SuKienIdRoute: typeof SuKienIdRoute
  SuKienIndexRoute: typeof SuKienIndexRoute
}

const SuKienRouteChildren: SuKienRouteChildren = {
  SuKienIdRoute: SuKienIdRoute,
  SuKienIndexRoute: SuKienIndexRoute,
}

const SuKienRouteWithChildren =
  SuKienRoute._addFileChildren(SuKienRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DoiTacRoute: DoiTacRoute,
  FeaturesRoute: FeaturesRoute,
  HocVienRoute: HocVienRoute,
  HomeRoute: HomeRoute,
  PortalRoute: PortalRoute,
  PricingRoute: PricingRoute,
  QisignalsRoute: QisignalsRoute,
  SanPhamRoute: SanPhamRouteWithChildren,
  SuKienRoute: SuKienRouteWithChildren,
  SurveyAuditRoute: SurveyAuditRoute,
  UltimaPartnershipRoute: UltimaPartnershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
